export const FeesABI = {
  address: '0x2033b72957c2f0b66cf5be479a2aa098d5bf18c36477907eba8be39435f2811',
  name: 'fees',
  friends: [],
  exposed_functions: [
    {
      name: 'create_resource_account',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'vector<u8>', 'vector<address>'],
      return: [],
    },
    {
      name: 'accept_admin',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
    {
      name: 'accept_reviewer',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
    {
      name: 'add_collector',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', '&signer', 'address'],
      return: [],
    },
    {
      name: 'add_currency',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'address'],
      return: [],
    },
    {
      name: 'check_collector_object',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'claim_fees',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'address'],
      return: [],
    },
    {
      name: 'create_collector_object',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
    {
      name: 'get_admin',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['address'],
    },
    {
      name: 'get_balance_to_claim',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address', 'address'],
      return: ['u64'],
    },
    {
      name: 'get_collectors',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['vector<address>'],
    },
    {
      name: 'get_currencies_addr',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['vector<address>'],
    },
    {
      name: 'get_pending_admin',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['address'],
    },
    {
      name: 'get_pending_reviewer',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['address'],
    },
    {
      name: 'get_resource_account_address',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['address'],
    },
    {
      name: 'get_resource_balances',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['vector<address>', 'vector<u64>'],
    },
    {
      name: 'get_reviewer',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['address'],
    },
    {
      name: 'payment',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'vector<address>', 'address', 'vector<u64>'],
      return: [],
    },
    {
      name: 'payment_v1',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [{ constraints: [] }],
      params: ['&signer', 'vector<address>', 'vector<u64>'],
      return: [],
    },
    {
      name: 'remove_collector',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', '&signer', 'address'],
      return: [],
    },
    {
      name: 'remove_currency',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'address'],
      return: [],
    },
    {
      name: 'remove_resource_account',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', '&signer'],
      return: [],
    },
    {
      name: 'resource_account_exists',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['bool'],
    },
    {
      name: 'set_pending_admin',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'address'],
      return: [],
    },
    {
      name: 'set_pending_reviewer',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'address'],
      return: [],
    },
  ],
  structs: [
    {
      name: 'Claimed',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'collector', type: 'address' },
        { name: 'amount', type: 'u64' },
        { name: 'currency', type: 'address' },
      ],
    },
    {
      name: 'Config',
      is_native: false,
      is_event: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        { name: 'admin_addr', type: 'address' },
        { name: 'pending_admin_addr', type: '0x1::option::Option<address>' },
        { name: 'reviewer_addr', type: 'address' },
        { name: 'pending_reviewer_addr', type: '0x1::option::Option<address>' },
        { name: 'currencies', type: 'vector<address>' },
      ],
    },
    {
      name: 'FeesAdmin',
      is_native: false,
      is_event: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        {
          name: 'signer_cap',
          type: '0x1::option::Option<0x1::account::SignerCapability>',
        },
        { name: 'fees_not_claimed', type: 'vector<u64>' },
        { name: 'currencies', type: 'vector<address>' },
        { name: 'collectors', type: 'vector<address>' },
      ],
    },
    {
      name: 'FeesToClaim',
      is_native: false,
      is_event: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        { name: 'currencies', type: 'vector<address>' },
        { name: 'amounts', type: 'vector<u64>' },
      ],
    },
  ],
} as const;
