export const SubscriptionABI = {
  address: '0x2033b72957c2f0b66cf5be479a2aa098d5bf18c36477907eba8be39435f2811',
  name: 'subscription',
  friends: [],
  exposed_functions: [
    {
      name: 'add_extension',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', '0x1::string::String', 'vector<u64>', 'u64'],
      return: [],
    },
    {
      name: 'buy_duration',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'vector<address>', 'u64', 'address'],
      return: [],
    },
    {
      name: 'buy_extension',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        'vector<address>',
        'vector<0x1::string::String>',
        'address',
      ],
      return: [],
    },
    {
      name: 'buy_plan',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        'u64',
        'vector<address>',
        'vector<0x1::string::String>',
        'address',
      ],
      return: [],
    },
    {
      name: 'claim_subscription',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
    {
      name: 'exists_subscription_plan',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['bool'],
    },
    {
      name: 'exists_user_subscription',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'get_app_status',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['bool'],
    },
    {
      name: 'get_move_bot_fields',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: [
        '0x2033b72957c2f0b66cf5be479a2aa098d5bf18c36477907eba8be39435f2811::subscription::MoveBotFields',
      ],
    },
    {
      name: 'get_plan',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: [
        'u64',
        'u64',
        'vector<0x2033b72957c2f0b66cf5be479a2aa098d5bf18c36477907eba8be39435f2811::subscription::Upgrade>',
        'bool',
      ],
    },
    {
      name: 'get_prices',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['vector<u64>'],
    },
    {
      name: 'get_subscription_config',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: [
        '0x2033b72957c2f0b66cf5be479a2aa098d5bf18c36477907eba8be39435f2811::subscription::SubscriptionPlan',
      ],
    },
    {
      name: 'get_subscription_to_claim',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: [
        '0x2033b72957c2f0b66cf5be479a2aa098d5bf18c36477907eba8be39435f2811::subscription::FreeSubscription',
      ],
    },
    {
      name: 'get_trial_duration',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['u64'],
    },
    {
      name: 'gift_subscription',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'address', 'u64'],
      return: [],
    },
    {
      name: 'has_extension_active',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address', '0x1::string::String'],
      return: ['bool'],
    },
    {
      name: 'has_subscription_active',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'has_subscription_to_claim',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'remove_extension',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', '0x1::string::String'],
      return: [],
    },
    {
      name: 'set_plan',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        'vector<u64>',
        'vector<address>',
        'vector<u64>',
        'address',
        '0x1::string::String',
        '0x1::string::String',
        'u64',
      ],
      return: [],
    },
    {
      name: 'set_trial_subscription_duration',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64'],
      return: [],
    },
    {
      name: 'trial_free_subscription',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
    {
      name: 'trigger_app',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
  ],
  structs: [
    {
      name: 'Upgrade',
      is_native: false,
      is_event: false,
      abilities: ['copy', 'drop', 'store', 'key'],
      generic_type_params: [],
      fields: [
        { name: 'name', type: '0x1::string::String' },
        { name: 'credits', type: 'u64' },
      ],
    },
    {
      name: 'CollectionAddressDiscount',
      is_native: false,
      is_event: false,
      abilities: ['copy', 'drop', 'store', 'key'],
      generic_type_params: [],
      fields: [
        { name: 'collection_addr', type: 'address' },
        { name: 'discount_per_day', type: 'u64' },
      ],
    },
    {
      name: 'Extension',
      is_native: false,
      is_event: false,
      abilities: ['copy', 'drop', 'store', 'key'],
      generic_type_params: [],
      fields: [
        { name: 'name', type: '0x1::string::String' },
        { name: 'prices', type: 'vector<u64>' },
        { name: 'credits', type: 'u64' },
      ],
    },
    {
      name: 'FreeSubscription',
      is_native: false,
      is_event: false,
      abilities: ['copy', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'account', type: 'address' },
        { name: 'duration', type: 'u64' },
      ],
    },
    {
      name: 'MoveBotFields',
      is_native: false,
      is_event: false,
      abilities: [],
      generic_type_params: [],
      fields: [
        { name: 'token_creator', type: 'address' },
        { name: 'token_collection', type: '0x1::string::String' },
        { name: 'token_name', type: '0x1::string::String' },
        { name: 'token_property_version', type: 'u64' },
      ],
    },
    {
      name: 'SubscriptionConfig',
      is_native: false,
      is_event: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        { name: 'stop_app', type: 'bool' },
        { name: 'trial_free_days', type: 'u64' },
      ],
    },
    {
      name: 'SubscriptionPlan',
      is_native: false,
      is_event: false,
      abilities: ['copy', 'key'],
      generic_type_params: [],
      fields: [
        { name: 'prices', type: 'vector<u64>' },
        {
          name: 'collections_discount',
          type: 'vector<0x2033b72957c2f0b66cf5be479a2aa098d5bf18c36477907eba8be39435f2811::subscription::CollectionAddressDiscount>',
        },
        {
          name: 'move_bot_id',
          type: '0x1::option::Option<0x3::token::TokenId>',
        },
        {
          name: 'extensions',
          type: 'vector<0x2033b72957c2f0b66cf5be479a2aa098d5bf18c36477907eba8be39435f2811::subscription::Extension>',
        },
      ],
    },
    {
      name: 'SubscriptionsGifted',
      is_native: false,
      is_event: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        {
          name: 'subscriptions',
          type: 'vector<0x2033b72957c2f0b66cf5be479a2aa098d5bf18c36477907eba8be39435f2811::subscription::FreeSubscription>',
        },
      ],
    },
    {
      name: 'UserSubscribed',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'account', type: 'address' },
        { name: 'start_time', type: 'u64' },
        { name: 'end_time', type: 'u64' },
        { name: 'price', type: 'u64' },
        { name: 'created_at', type: 'u64' },
        {
          name: 'upgrades',
          type: 'vector<0x2033b72957c2f0b66cf5be479a2aa098d5bf18c36477907eba8be39435f2811::subscription::Upgrade>',
        },
        { name: 'trial_version', type: 'bool' },
      ],
    },
    {
      name: 'UserSubscription',
      is_native: false,
      is_event: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        { name: 'start_time', type: 'u64' },
        { name: 'end_time', type: 'u64' },
        {
          name: 'upgrades',
          type: 'vector<0x2033b72957c2f0b66cf5be479a2aa098d5bf18c36477907eba8be39435f2811::subscription::Upgrade>',
        },
        { name: 'trial_version', type: 'bool' },
      ],
    },
  ],
} as const;
