export const FeesABI = {
  address: '0x28af3805f23612b4dfa86202a454f5144159702559aea86393ac0d50f577568d',
  name: 'fees_beta_1',
  friends: [],
  exposed_functions: [
    {
      name: 'accept_admin',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
    {
      name: 'accept_reviewer',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
    {
      name: 'add_collector',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', '&signer', 'address'],
      return: [],
    },
    {
      name: 'check_collector_object',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'claim_salary',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
    {
      name: 'create_collector_object',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
    {
      name: 'create_resource_account',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'vector<u8>', 'vector<address>'],
      return: [],
    },
    {
      name: 'get_admin',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['address'],
    },
    {
      name: 'get_balance_to_claim',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['u64'],
    },
    {
      name: 'get_collectors',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['vector<address>'],
    },
    {
      name: 'get_currency_addr',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['address'],
    },
    {
      name: 'get_pending_admin',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['address'],
    },
    {
      name: 'get_pending_reviewer',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['address'],
    },
    {
      name: 'get_resource_account_address',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['address'],
    },
    {
      name: 'get_resource_balance',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['u64'],
    },
    {
      name: 'get_reviewer',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['address'],
    },
    {
      name: 'payment',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'vector<address>', 'vector<u64>'],
      return: [],
    },
    {
      name: 'remove_collector',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', '&signer', 'address'],
      return: [],
    },
    {
      name: 'remove_resource_account',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', '&signer'],
      return: [],
    },
    {
      name: 'resource_account_exists',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['bool'],
    },
    {
      name: 'set_currency',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'address'],
      return: [],
    },
    {
      name: 'set_pending_admin',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'address'],
      return: [],
    },
    {
      name: 'set_pending_reviewer',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'address'],
      return: [],
    },
  ],
  structs: [
    {
      name: 'Claimed',
      is_native: false,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'collector', type: 'address' },
        { name: 'amount', type: 'u64' },
      ],
    },
    {
      name: 'Config',
      is_native: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        { name: 'admin_addr', type: 'address' },
        { name: 'pending_admin_addr', type: '0x1::option::Option<address>' },
        { name: 'reviewer_addr', type: 'address' },
        { name: 'pending_reviewer_addr', type: '0x1::option::Option<address>' },
        { name: 'currency', type: '0x1::option::Option<address>' },
      ],
    },
    {
      name: 'FeesAdmin',
      is_native: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        {
          name: 'signer_cap',
          type: '0x1::option::Option<0x1::account::SignerCapability>',
        },
        { name: 'salary_not_claimed', type: 'u64' },
        { name: 'collectors', type: 'vector<address>' },
      ],
    },
    {
      name: 'FeesToClaim',
      is_native: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [{ name: 'amount', type: 'u64' }],
    },
  ],
} as const;
