export const SubscriptionABI = {
  address: '0x28af3805f23612b4dfa86202a454f5144159702559aea86393ac0d50f577568d',
  name: 'subscription_v3',
  friends: [],
  exposed_functions: [
    {
      name: 'buy_plan',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', 'vector<address>'],
      return: [],
    },
    {
      name: 'claim_subscription',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
    {
      name: 'get_move_bot_fields',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: [
        '0x28af3805f23612b4dfa86202a454f5144159702559aea86393ac0d50f577568d::subscription_v3::MoveBotFields',
      ],
    },
    {
      name: 'get_plan',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['u64', 'u64'],
    },
    {
      name: 'get_prices',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['vector<u64>'],
    },
    {
      name: 'get_subscription_config',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: [
        '0x28af3805f23612b4dfa86202a454f5144159702559aea86393ac0d50f577568d::subscription_v3::SubscriptionPlan',
      ],
    },
    {
      name: 'gift_subscription',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'address', 'u64'],
      return: [],
    },
    {
      name: 'has_subscription_active',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'set_plan',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        'vector<u64>',
        'vector<address>',
        'vector<u64>',
        'address',
        '0x1::string::String',
        '0x1::string::String',
        'u64',
      ],
      return: [],
    },
  ],
  structs: [
    {
      name: 'CollectionAddressDiscount',
      is_native: false,
      is_event: false,
      abilities: ['copy', 'drop', 'store', 'key'],
      generic_type_params: [],
      fields: [
        { name: 'collection_addr', type: 'address' },
        { name: 'discount_per_day', type: 'u64' },
      ],
    },
    {
      name: 'FreeSubscription',
      is_native: false,
      is_event: false,
      abilities: ['copy', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'account', type: 'address' },
        { name: 'duration', type: 'u64' },
      ],
    },
    {
      name: 'MoveBotFields',
      is_native: false,
      is_event: false,
      abilities: [],
      generic_type_params: [],
      fields: [
        { name: 'token_creator', type: 'address' },
        { name: 'token_collection', type: '0x1::string::String' },
        { name: 'token_name', type: '0x1::string::String' },
        { name: 'token_property_version', type: 'u64' },
      ],
    },
    {
      name: 'SubscriptionPlan',
      is_native: false,
      is_event: false,
      abilities: ['copy', 'key'],
      generic_type_params: [],
      fields: [
        { name: 'prices', type: 'vector<u64>' },
        {
          name: 'collections_discount',
          type: 'vector<0x28af3805f23612b4dfa86202a454f5144159702559aea86393ac0d50f577568d::subscription_v3::CollectionAddressDiscount>',
        },
        {
          name: 'move_bot_id',
          type: '0x1::option::Option<0x3::token::TokenId>',
        },
      ],
    },
    {
      name: 'SubscriptionsGifted',
      is_native: false,
      is_event: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        {
          name: 'subscriptions',
          type: 'vector<0x28af3805f23612b4dfa86202a454f5144159702559aea86393ac0d50f577568d::subscription_v3::FreeSubscription>',
        },
      ],
    },
    {
      name: 'UserSubscribed',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'account', type: 'address' },
        { name: 'start_time', type: 'u64' },
        { name: 'end_time', type: 'u64' },
        { name: 'price', type: 'u64' },
        { name: 'created_at', type: 'u64' },
      ],
    },
    {
      name: 'UserSubscription',
      is_native: false,
      is_event: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        { name: 'start_time', type: 'u64' },
        { name: 'end_time', type: 'u64' },
      ],
    },
  ],
} as const;
