export const SubscriptionABI = {
  address: '0x1cdcbae7369dc8e159bc8bf951cfb7e7e168ef1bd56c169dcacb336b13657417',
  name: 'subscription',
  friends: [],
  exposed_functions: [
    {
      name: 'buy_plan',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [{ constraints: [] }],
      params: ['&signer', 'u64', 'vector<address>'],
      return: [],
    },
    {
      name: 'claim_subscription',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
    {
      name: 'get_plan',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['u64', 'u64'],
    },
    {
      name: 'get_price_per_day',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ['u64'],
    },
    {
      name: 'gift_subscription',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'address', 'u64'],
      return: [],
    },
    {
      name: 'has_subscription_active',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'set_plan',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        'address',
        'u64',
        'vector<address>',
        'vector<u64>',
        '0x1::object::Object<0x1cdcbae7369dc8e159bc8bf951cfb7e7e168ef1bd56c169dcacb336b13657417::subscription::MoveBot>',
      ],
      return: [],
    },
  ],
  structs: [
    {
      name: 'CollectionAddressDiscount',
      is_native: false,
      is_event: false,
      abilities: ['copy', 'drop', 'store', 'key'],
      generic_type_params: [],
      fields: [
        { name: 'collection_addr', type: 'address' },
        { name: 'discount_per_day', type: 'u64' },
      ],
    },
    {
      name: 'FreeSubscription',
      is_native: false,
      is_event: false,
      abilities: ['copy', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'account', type: 'address' },
        { name: 'duration', type: 'u64' },
      ],
    },
    {
      name: 'MoveBot',
      is_native: false,
      is_event: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [{ name: 'nft_id', type: '0x3::token::TokenId' }],
    },
    {
      name: 'SubscriptionPlan',
      is_native: false,
      is_event: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        { name: 'coin', type: 'address' },
        { name: 'price_per_day', type: 'u64' },
        {
          name: 'collections_discount',
          type: 'vector<0x1cdcbae7369dc8e159bc8bf951cfb7e7e168ef1bd56c169dcacb336b13657417::subscription::CollectionAddressDiscount>',
        },
        {
          name: 'move_bot_id',
          type: '0x1::option::Option<0x3::token::TokenId>',
        },
      ],
    },
    {
      name: 'SubscriptionsGifted',
      is_native: false,
      is_event: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        {
          name: 'subscriptions',
          type: 'vector<0x1cdcbae7369dc8e159bc8bf951cfb7e7e168ef1bd56c169dcacb336b13657417::subscription::FreeSubscription>',
        },
      ],
    },
    {
      name: 'UserSubscribed',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'account', type: 'address' },
        { name: 'start_time', type: 'u64' },
        { name: 'end_time', type: 'u64' },
        { name: 'price', type: 'u64' },
        { name: 'created_at', type: 'u64' },
      ],
    },
    {
      name: 'UserSubscription',
      is_native: false,
      is_event: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        { name: 'start_time', type: 'u64' },
        { name: 'end_time', type: 'u64' },
      ],
    },
  ],
} as const;
